<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QGMO3TS" failures="4" tests="27" name="testCases.CRMTest" time="68.221" errors="0" timestamp="2025-07-02T16:37:12 IST" skipped="9">
  <testcase classname="testCases.CRMTest" name="verifyPageIsCRM_UsersPage" time="1.085"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNullUserName" time="1.381"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNullMobileNumber" time="1.686"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNullHandle" time="1.875"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNullEmail" time="2.204"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNullDepartment" time="2.498"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyTotalUserCountOnPagination" time="7.762"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifySearchByUserName" time="3.114"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNullConditionValueInFilter" time="2.878"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyFilterBy_Name_Contains" time="5.564"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyFilterBy_Name_DoesNotContains" time="5.738"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyFilterBy_Email_IsEqual" time="5.519"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyFilterBy_Email_IsNotEqual" time="5.595"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyFilterBy_Mobile_EndsWith" time="5.743"/>
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyFilterBy_Mobile_StartsWith" time="5.605">
    <failure message="The following asserts failed:
	Data is not available as per filter expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Data is not available as per filter expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testCases.CRMTest.verifyFilterBy_Mobile_StartsWith(CRMTest.java:297)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyFilterBy_Mobile_StartsWith -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNullGroupName" time="1.432">
    <failure message="The following asserts failed:
	Data is not available as per filter expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Data is not available as per filter expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testCases.CRMTest.verifyNullGroupName(CRMTest.java:325)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyNullGroupName -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyTotalGroupCountOnPagination" time="5.269">
    <failure message="The following asserts failed:
	Data is not available as per filter expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Data is not available as per filter expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testCases.CRMTest.verifyTotalGroupCountOnPagination(CRMTest.java:366)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyTotalGroupCountOnPagination -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifySearchByGroupName" time="3.273">
    <failure message="The following asserts failed:
	Data is not available as per filter expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Data is not available as per filter expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testCases.CRMTest.verifySearchByGroupName(CRMTest.java:376)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifySearchByGroupName -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyDownloadSampleCSV">
    <skipped/>
  </testcase> <!-- verifyDownloadSampleCSV -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyDeleteSpecificUser">
    <skipped/>
  </testcase> <!-- verifyDeleteSpecificUser -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyUploadBulkUserFile">
    <skipped/>
  </testcase> <!-- verifyUploadBulkUserFile -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNewUserCreationWithValidData">
    <skipped/>
  </testcase> <!-- verifyNewUserCreationWithValidData -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyGroupNameCreationWithValidDate">
    <skipped/>
  </testcase> <!-- verifyGroupNameCreationWithValidDate -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyDuplicateGroupNameCreation">
    <skipped/>
  </testcase> <!-- verifyDuplicateGroupNameCreation -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNewUserCreationWithDuplicateEmail">
    <skipped/>
  </testcase> <!-- verifyNewUserCreationWithDuplicateEmail -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyEditUserbyUpdatingName">
    <skipped/>
  </testcase> <!-- verifyEditUserbyUpdatingName -->
  <system-out/>
  <testcase classname="testCases.CRMTest" name="verifyNewUserCreationWithDuplicateHandle">
    <skipped/>
  </testcase> <!-- verifyNewUserCreationWithDuplicateHandle -->
  <system-out/>
</testsuite> <!-- testCases.CRMTest -->
